### ISSUE TITLE
/multi_path.app/iosbinpack64//bin/bash: No such file or directory ?

### ISSUE THREAD

**Issue by SeaJae** [jakeajames/multi_path#8]
Just grabbed the new code...worked the 1st time...now everytime after the first run i get this when I ssh in..

login as: root
root@172.17.25.16's password:
[267] Jul 02 11:29:19 lastlog_perform_login: Couldn't stat /var/log/lastlog: No such file or directory
[267] Jul 02 11:29:19 lastlog_openseek: /var/log/lastlog is not a file or directory!
Enjoy SSH! ~@ Jakeashacks
- bash :  / var / containers / Bundle / Application / BBDD6CCB-43D4-4337-8AD5-926F076C2993 / multi_path.app / iosbinpack64 / / bin / bash: No such file or directory
Iphone:~ root#

i will see if I can figure it out and let you know...

**Comment by SeaJae** [comment]
Okay I deleted and cloned the code locally again..  recompiled and its working again.    I guess its very particular the directory on the MAC it runs from.

**Comment by aassq115533** [comment]
line inside kern_utils.m crashes: uint64_t context = zm_fix_addr(kexecute(ksym_vfs_context_current + kslide, 1, 0, 0, 0, 0, 0, 0));

because of this line in kexecute.c:
uint64_t returnval = IOConnectTrap6(user_client, 0, (uint64_t)(x1), (uint64_t)(x2), (uint64_t)(x3), (uint64_t)(x4), (uint64_t)(x5), (uint64_t)(x6));.

Running on iPhone 6 11.3.1.
Offsets are:
uint64_t ksym_vnode_lookup = 0xfffffff0071db710;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9a04;
